plugins=(
    git
    docker
    dotenv
)

# export ZSH_THEME=agnoster
export ENABLE_CORRECTION=false

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

export EDITOR=vim
export SSH_KEY_PATH=~/.ssh/id_rsa
export NVM_DIR="$HOME/.nvm"

[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"

alias vim=$EDITOR

if which rbenv > /dev/null; then
	eval "$(rbenv init -)"
fi